= Anhang

#include("is-state/is-state.typ")
#pagebreak()
#include("research-workshop/leitfäden.typ")
#pagebreak()
#include("research-results/research-results.typ")
#pagebreak()
#include("ideation/ideation.typ")
#pagebreak()
#include("konzept/konzept.typ")
#pagebreak()
#include("prototype/prototype.typ")
#pagebreak()
#include("validierung/validierung.typ")